### ISSUE TITLE
Redesign the login page

### ISSUE THREAD

**Issue by thebishaldeb** [thebishaldeb/Instances#1]
Currently the login page isn't that appealing. A new look would be appreciated.

**Comment by ericNunnDev** [comment]
Any preferences in the direction of the design or technologies you want involved? I am a ReactJS developer and would be happy to help with this.

**Comment by thebishaldeb** [comment]
I've not actually used reactJs in this project. It only uses ejs. Not any specific designing but would love it if it goes along with the theme of the website. Also it uses bootstrap.

**Comment by ericNunnDev** [comment]
Awesome. I am also fluent in ES6, so that should not be a problem. I'll see what I can come up with for you!

**Comment by thebishaldeb** [comment]
Sure.
